#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source_sh () {
  emulate -LR sh
  . "$@"
}

source_sh ~/.profile

HISTFILE=~/.histfile
HISTSIZE=900000
SAVEHIST=900000
setopt appendhistory autocd
unsetopt extendedglob nomatch notify

DIRSTACKSIZE=20
setopt autopushd pushdsilent pushdtohome

## Remove duplicate entries
setopt pushdignoredups

## This reverts the +/- operators.
setopt pushdminus

